name: Demo Build

on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: self-hosted

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Perform the build
      - name: Build MGI Solution Explorer Solution
        run: mgislnexp build "Sample Files\Sample Solution.lvsln" Release -version x.x.x.$env:GITHUB_RUN_NUMBER

      # Store Build Items
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Build Items
          path: |
            Sample Files\builds
